### ISSUE TITLE
Plugin isn`t working with 8.2 server

### ISSUE THREAD

**Issue by ky0uraku** [Spoffy/EcoDiscordPlugin#29]
[08:25:06.807] [1] [ Info] [Eco] Failed to load server, Exception was Exception: MissingMethodException
Message:Method not found: 'Void Eco.Core.Plugins.PluginConfig`1..ctor(System.String, Boolean)'.
Source:DiscordLinkUnified

System.MissingMethodException: Method not found: 'Void Eco.Core.Plugins.PluginConfig`1..ctor(System.String, Boolean)'.
   at Eco.Plugins.DiscordLink.DiscordLink.SetupConfig()
   at Eco.Plugins.DiscordLink.DiscordLink..ctor()

**Comment by TheKye** [comment]
This was fixed with his latest release :)
