### ISSUE TITLE
[2.0] Unhandled NullReferenceException UpdateEcoStatus

### ISSUE THREAD

**Issue by yland4** [Spoffy/EcoDiscordPlugin#68]
[12:39:35] Initializing DiscordLink... 
[12:39:36] [DiscordLink] Connected to Discord
[12:39:36] Initializing DiscordLink... Finished in 856.4ms

[12:39:40] Saving world... 
[12:39:41] [DiscordLink] Channel Link Verified: DD214-EcoGaming - game-chat <--> General (Chat Link)
[12:39:41] [DiscordLink] Channel Link Verified: DD214-EcoGaming - eco-status (Eco Status)
[12:39:41] [DiscordLink] All channel links sucessfully verified
[12:39:48] Saving world... Finished in 7,925.6ms
[12:39:48] [Server Initialization]... Finished in 53,353.6ms
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Plugins.DiscordLink.DiscordLink.UpdateEcoStatus()
   at Eco.Plugins.DiscordLink.DiscordLink.<SetUpClient>b__29_7(Object innerArgs)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by MonzUn** [comment]
Likely related to EcoStatus failing to find the correct message.

**Comment by yland4** [comment]
Bug was from a message already in that channel. discord link bot didnt know what to do and got confused. Deleted all messages in that channel and it works like a charm.

**Comment by yland4** [comment]
Thanks for the quick response and helping me figure this out!
